### ISSUE TITLE
Missing required argument -accessUrl

### ISSUE THREAD

**Issue by HalianElf** [Starbix/docker-synclounge#1]
New build isn't passing the domain right:
```root@nas:/$ docker run \
> --name=synclounge \
> -p 8088:8088 \
> -p 8089:8089 \
> -e DOMAIN=redacted.com \
> starbix/synclounge

> SyncLounge@2.0.0 server /opt/synclounge
> node server.js

Settings { webroot: '',
  serverroot: '',
  accessUrl: '',
  autoJoin: false,
  autoJoinServer: '',
  autoJoinRoom: '',
  autoJoinPassword: '' }
Missing required argument -accessUrl. EG. "node webapp.js -accessUrl=http://sl.example.com". This URL is used for redirecting invite links.
Error bootstrapping webapp: Error: Missing URL for invite links
    at Promise (/opt/synclounge/webapp.js:25:21)
    at new Promise (<anonymous>)
    at bootstrap (/opt/synclounge/webapp.js:21:10)
    at Object.<anonymous> (/opt/synclounge/webapp.js:125:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)```

**Comment by samcm** [comment]
Working on it :)

**Comment by samcm** [comment]
Should be fixed now - just waiting on Dockerhub to build the new images.

**Comment by HalianElf** [comment]
Thank you!
